# Generated by Django 4.2.4 on 2023-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='модель автомобиля')),
                ('make', models.CharField(max_length=100, verbose_name='марка автомобиля')),
                ('year', models.EmailField(max_length=254, verbose_name='год выпуска автомобиля')),
                ('color', models.CharField(max_length=50, verbose_name='цвет автомобиля')),
                ('milage', models.IntegerField(verbose_name='пробег автомобиля')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='тип топлива')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена аренды в день')),
                ('avaibilaty_status', models.BooleanField(verbose_name='статус доступности: true/false')),
            ],
        ),
    ]
